"""TokenCipher — authenticated symmetric encryption for sensitive credentials.

We never want WhatsApp/Meta access tokens, OpenRouter API keys, or buyer PII
sitting in the database as plaintext: if the DB is dumped or a backup leaks,
the blast radius is everything. This module wraps AES-256-GCM (the AEAD primitive
recommended by NIST SP 800-38D) behind a small string-in / string-out API so the
rest of the codebase doesn't touch crypto directly.

The encryption key is a 32-byte secret loaded from ``APP_ENCRYPTION_KEY``
(base64-encoded). Generate one with :func:`generate_key`. Rotate by re-encrypting
under a new key — there is no in-place rotation in v1; that's a P14 feature.
"""

from __future__ import annotations

import base64
import os
import secrets

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

# Encoded payload layout: ``b64( nonce(12) || ciphertext_and_tag )``. We use
# url-safe base64 with no padding so encrypted strings round-trip cleanly through
# JSON, query strings, and most database column types without escaping surprises.
_NONCE_BYTES = 12
_KEY_BYTES = 32  # AES-256


class CryptoError(RuntimeError):
    """Encryption or decryption failed (bad key, tampered ciphertext, malformed input)."""

    code = "sample.security.crypto"


def generate_key() -> str:
    """Return a new base64-encoded 32-byte key suitable for :class:`TokenCipher`.

    Use this once at deploy time to populate ``APP_ENCRYPTION_KEY``; treat
    the value like any other root credential (vault / sealed secret / KMS).
    """
    return base64.urlsafe_b64encode(secrets.token_bytes(_KEY_BYTES)).decode("ascii")


def key_from_env(var: str = "APP_ENCRYPTION_KEY") -> bytes:
    """Load + decode the encryption key from an env var.

    Raises :class:`CryptoError` if the variable is missing or doesn't decode to
    exactly 32 bytes — refuse to start rather than silently use a weak key.
    """
    raw = os.environ.get(var, "")
    if not raw:
        raise CryptoError(f"missing env var: {var}")
    try:
        key = base64.urlsafe_b64decode(_pad(raw))
    except (ValueError, TypeError) as exc:
        raise CryptoError(f"{var} is not valid base64") from exc
    if len(key) != _KEY_BYTES:
        raise CryptoError(f"{var} must decode to {_KEY_BYTES} bytes (got {len(key)})")
    return key


def _pad(value: str) -> str:
    # urlsafe_b64decode is strict about padding; tolerate keys generated by tools
    # that strip it (it's safe — base64 padding carries no entropy).
    missing = (-len(value)) % 4
    return value + ("=" * missing)


class TokenCipher:
    """AES-256-GCM cipher with a fresh random nonce per call.

    ``encrypt`` returns an opaque base64 string; ``decrypt`` either returns the
    original plaintext or raises :class:`CryptoError`. Never log the raw key.
    """

    def __init__(self, key: bytes) -> None:
        if len(key) != _KEY_BYTES:
            raise CryptoError(f"key must be {_KEY_BYTES} bytes; got {len(key)}")
        self._aead = AESGCM(key)

    @classmethod
    def from_env(cls, var: str = "APP_ENCRYPTION_KEY") -> TokenCipher:
        return cls(key_from_env(var))

    def encrypt(self, plaintext: str, *, associated_data: bytes | None = None) -> str:
        nonce = secrets.token_bytes(_NONCE_BYTES)
        try:
            ct = self._aead.encrypt(nonce, plaintext.encode("utf-8"), associated_data)
        except Exception as exc:  # pragma: no cover — defensive
            raise CryptoError(f"encrypt failed: {exc}") from exc
        return base64.urlsafe_b64encode(nonce + ct).decode("ascii").rstrip("=")

    def decrypt(self, token: str, *, associated_data: bytes | None = None) -> str:
        try:
            blob = base64.urlsafe_b64decode(_pad(token))
        except (ValueError, TypeError) as exc:
            raise CryptoError("token is not valid base64") from exc
        if len(blob) <= _NONCE_BYTES:
            raise CryptoError("token shorter than the nonce — malformed")
        nonce, ct = blob[:_NONCE_BYTES], blob[_NONCE_BYTES:]
        try:
            pt = self._aead.decrypt(nonce, ct, associated_data)
        except InvalidTag as exc:
            # AEAD authentication failed: wrong key, wrong AAD, or the
            # ciphertext was modified. Never reveal which to the caller.
            raise CryptoError("decrypt failed: authentication tag mismatch") from exc
        return pt.decode("utf-8")
