#!/usr/bin/env bash
# infra/scripts/bootstrap.sh — one-shot bring-up for a fresh Ubuntu 24.04 VPS.
#
# Idempotent: re-running is safe and only installs what's missing.
# Usage:  sudo bash infra/scripts/bootstrap.sh sample.example.com you@example.com
set -euo pipefail

DOMAIN="${1:?usage: bootstrap.sh <domain> <email>}"
EMAIL="${2:?usage: bootstrap.sh <domain> <email>}"
REPO_DIR="${REPO_DIR:-/opt/sample}"
ENV_FILE="${REPO_DIR}/.env.prod"

log() { printf '\033[1;34m[bootstrap]\033[0m %s\n' "$*"; }
need_root() { [[ $EUID -eq 0 ]] || { echo "must run as root" >&2; exit 1; }; }

need_root

# 1. System packages -------------------------------------------------------
log "installing apt packages (docker, certbot, ufw, envsubst)…"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y \
    ca-certificates curl gnupg lsb-release ufw \
    docker.io docker-compose-plugin \
    certbot \
    gettext-base \
    fail2ban

systemctl enable --now docker

# 2. Firewall (allow ssh + http + https only) ------------------------------
log "configuring ufw…"
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow OpenSSH
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable

# 3. Repo location ---------------------------------------------------------
if [[ ! -d "${REPO_DIR}/.git" ]]; then
    log "cloning repo into ${REPO_DIR} (set REPO_URL to override the default)…"
    REPO_URL="${REPO_URL:-https://github.com/fmonfasani/sample.git}"
    git clone "${REPO_URL}" "${REPO_DIR}"
else
    log "repo already at ${REPO_DIR} — pulling latest"
    git -C "${REPO_DIR}" pull --ff-only
fi

# 4. .env.prod template ----------------------------------------------------
if [[ ! -f "${ENV_FILE}" ]]; then
    log "writing initial ${ENV_FILE} (fill in the placeholders!)"
    cat > "${ENV_FILE}" <<EOF
# Generated by bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Fill in every <CHANGE_ME> value before running deploy.sh.

APP_ENV=production
APP_LOG_LEVEL=INFO

# Postgres (internal — never exposed)
POSTGRES_DB=sample
POSTGRES_USER=sample
POSTGRES_PASSWORD=$(openssl rand -hex 24)

# Encryption key for sensitive tokens (32 bytes, base64-urlsafe)
APP_ENCRYPTION_KEY=$(python3 -c 'import secrets,base64; print(base64.urlsafe_b64encode(secrets.token_bytes(32)).decode())')

# Rate limits (per-IP). Adjust based on observed traffic.
APP_RATE_LIMIT_DEFAULT=120/minute
APP_RATE_LIMIT_WEBHOOK=600/minute
APP_RATE_LIMIT_ONBOARD=30/minute

# Public-facing domain for the dashboard (CORS)
APP_DASHBOARD_ORIGINS=https://${DOMAIN}

# --- LLM ------------------------------------------------------------------
OPENROUTER_API_KEY=<CHANGE_ME>

# --- WhatsApp / Meta ------------------------------------------------------
META_APP_SECRET=<CHANGE_ME>
META_VERIFY_TOKEN=$(openssl rand -hex 16)
KAPSO_GATEWAY_URL=<CHANGE_ME>
EOF
    chmod 600 "${ENV_FILE}"
fi

# 5. TLS certs via certbot (webroot mode — nginx hasn't started yet) -------
log "obtaining TLS cert for ${DOMAIN}…"
mkdir -p /var/www/certbot
if [[ ! -d "/etc/letsencrypt/live/${DOMAIN}" ]]; then
    # Standalone for the very first cert (no nginx yet to serve the challenge).
    certbot certonly --standalone --non-interactive --agree-tos \
        --email "${EMAIL}" -d "${DOMAIN}" \
        --pre-hook "systemctl stop nginx || true" \
        --deploy-hook "/usr/local/bin/sample-reload-nginx || true"
fi

# 6. Render nginx.conf with the domain in place ----------------------------
log "rendering nginx config…"
export APP_DOMAIN="${DOMAIN}"
envsubst '${APP_DOMAIN}' < "${REPO_DIR}/infra/nginx/nginx.conf" \
    > "${REPO_DIR}/infra/nginx/nginx.rendered.conf"
# Atomically swap the rendered conf into place so docker-compose mounts it.
mv "${REPO_DIR}/infra/nginx/nginx.rendered.conf" "${REPO_DIR}/infra/nginx/nginx.conf.live"

# 7. Systemd unit for boot-time bring-up ----------------------------------
log "installing systemd unit…"
install -m 0644 "${REPO_DIR}/infra/systemd/app.service" /etc/systemd/system/
systemctl daemon-reload
systemctl enable app.service

# 8. Cert renewal hook ----------------------------------------------------
cat > /usr/local/bin/sample-reload-nginx <<'EOF'
#!/usr/bin/env bash
docker compose -f /opt/sample/infra/docker/docker-compose.prod.yml exec nginx nginx -s reload || true
EOF
chmod +x /usr/local/bin/sample-reload-nginx

# Certbot's apt package installs a systemd timer for auto-renewal already;
# wire our reload hook in via /etc/letsencrypt/renewal-hooks/deploy/
mkdir -p /etc/letsencrypt/renewal-hooks/deploy
cp /usr/local/bin/sample-reload-nginx /etc/letsencrypt/renewal-hooks/deploy/

log "bootstrap done. Next: edit ${ENV_FILE}, then run infra/scripts/deploy.sh"
